export const NicheMatrix: Record<string, string[]> = {
    'FINANCE & WEALTH': ['Dividend Growth Investing', 'High-Income Side Hustles', 'Real Estate Investing', 'ETF Investing for Beginners', 'AI Personal Investing Tools', 'Crypto', 'Financial Freedom (FIRE)', 'Tax Saving Strategies', 'Passive Income (Digital Products)', 'Millionaire Money Habits'],
    'FITNESS & DIET': ['Weight Loss for Men Over 35', 'Natural Testosterone Optimization', 'High-Protein Meal Prep', 'Home Workouts (No Equipment)', 'Muscle Building After 40', 'Intermittent Fasting for Fat Loss', 'Longevity & Healthy Aging', 'Walking for Fat Loss', 'Biohacking for Better Health', 'Sleep Optimization & Recovery'],
    'TECH & FUTURE AI': ['AI Tools for Business Owners', 'AI Automation Workflows', 'ChatGPT for Productivity', 'AI Side Hustles', 'AI Agents for Small Businesses', 'No-Code AI App Development', 'AI Video Creation', 'Cybersecurity in the AI Era', 'Humanoid Robots & Robotics', 'Future AI Jobs & Careers'],
    'MOTIVATION & MINDSET': ['Stoicism for Modern Men', 'Self-Discipline Systems', 'Morning Routines of Millionaires', 'Deep Work & Focus', 'Mental Toughness Training', 'Building Unshakable Confidence', 'Breaking Bad Habits', 'Productivity Systems', 'Goal Achievement Frameworks', 'Resilience After Failure'],
    'BUSINESS & STARTUPS': ['AI SaaS Startup Ideas', 'One-Person Businesses', 'B2B Lead Generation Systems', 'Sales Funnels That Convert', 'High-Ticket Consulting Businesses', 'Shopify Brand Growth', 'Subscription Business Models', 'LinkedIn Personal Branding', 'Agency Growth Strategies', 'Startup Case Studies'],
    'TRAVEL & EXPLORATION': ['Hidden European Destinations', 'Luxury Travel on a Budget', 'Digital Nomad Cities', 'National Parks Adventures', 'Solo Travel Safety', 'Food Tourism Around the World', 'Remote Islands & Secret Beaches', 'Budget Backpacking', 'Scenic Road Trips', 'Adventure Travel Experiences'],
    'HUMAN PSYCHOLOGY': ['Dark Psychology Explained', 'Body Language Analysis', 'Cognitive Biases in Daily Life', 'Emotional Intelligence', 'Persuasion & Influence', 'Psychology of Attraction', 'Habit Formation Science', 'Social Status & Human Behavior', 'Manipulation Tactics (Educational)', 'Decision-Making Psychology'],
    'SCIENCE & SPACE': ['James Webb Space Discoveries', 'Black Holes Explained', 'Mars Colonization', 'Quantum Computing', 'Neuroscience & the Brain', 'Longevity Research', 'Fusion Energy', 'Search for Alien Life', 'Future Space Missions', 'Ancient Mysteries Explained by Science'],
    'POP CULTURE & MEDIA': ['YouTube Algorithm Secrets', 'Creator Economy Trends', 'Celebrity Business Empires', 'Streaming Platform Wars', 'Viral Marketing Campaigns', 'Movie Easter Eggs & Hidden Details', 'Music Industry Business', 'Internet Culture & Memes', 'Social Media Growth Strategies', 'Brand Success Stories'],
    'UNTOLD HISTORY': ['Lost Civilizations (Atlantis, Göbekli Tepe, etc.)', 'Secret Military Projects', 'Cold War Spy Stories', 'Ancient Engineering Mysteries', 'Forgotten Empires', 'History\'s Greatest Heists', 'Hidden Treasure Legends', 'Archaeological Discoveries', 'Historical Conspiracies (Evidence-Based)', 'Unsolved Historical Mysteries']
};
